[profile.default]
src = "contracts"
out = "out"
libs = ["node_modules", "lib"]
remappings = [
  "forge-std/=lib/forge-std/src/",
  "@openzeppelin/contracts/=node_modules/@openzeppelin/contracts/"
]
solc = "0.8.20"
